### ISSUE TITLE
Can I use FIO test the target which is connected by jscsi?

### ISSUE THREAD

**Issue by Pantyhose-S** [sebastiangraf/jSCSI#38]
I am using jscsi to connect a server's target.
I can do write/read in my java code.
But I need to use  some tools to test the disk, like IOMeter or FIO.
How can I do this? 
Can I mount the target connected by jscsi as a disk driver like open-scsi?

**Comment by sebastiangraf** [comment]
@Pantyhose-S  I guess you use the initiator and not the target from jscsi? In that case, you either have the ability to benchmark through java or somehow to provide kind of bridge in an own piece of source code...
Besides, I tested the target part with some tools like fio, but never the initiator.

**Comment by sebastiangraf** [comment]
I'll close this issue, feel free to open it again for further questions.
